import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import {NavBar, Footer} from "@/components";

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto.className}`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
